/**
 * 🚨 GENERATED FILE - DO NOT EDIT MANUALLY 🚨
 * 
 * This file is automatically generated from backend database enum definitions.
 * 
 * Source: backend/db/enums/*.enum.ts
 * Generated: 2025-06-21T17:29:08.519Z
 * 
 * To update these types:
 * 1. Modify the enum values in backend/db/enums/*.enum.ts
 * 2. Run: npm run generate:types (or node scripts/generate-frontend-types.js)
 * 
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY - Your changes will be overwritten!
 */

// ====================================
// TYPE DEFINITIONS
// ====================================

export type EmployeeStatus = 'Active' | 'On Leave' | 'Inactive';

export type JobGrade = 'JT' | 'T' | 'ST' | 'EN' | 'SE' | 'C' | 'SC' | 'SM';

export type OpportunityLevel = 'Low' | 'Medium' | 'High';

export type OpportunityStatus = 'In Progress' | 'On Hold' | 'Done';

export type PersonStatus = 'candidate' | 'employee' | 'former_employee' | 'inactive';

export type RoleStatus = 'Open' | 'Staffed' | 'Won' | 'Lost';

export type WorkStatus = 'On Project' | 'On Bench' | 'Available';

// ====================================
// RUNTIME CONSTANTS
// ====================================

export const EMPLOYEE_STATUS_VALUES: readonly EmployeeStatus[] = ['Active', 'On Leave', 'Inactive'] as const;

export const JOB_GRADE_VALUES: readonly JobGrade[] = ['JT', 'T', 'ST', 'EN', 'SE', 'C', 'SC', 'SM'] as const;

export const OPPORTUNITY_LEVEL_VALUES: readonly OpportunityLevel[] = ['Low', 'Medium', 'High'] as const;

export const OPPORTUNITY_STATUS_VALUES: readonly OpportunityStatus[] = ['In Progress', 'On Hold', 'Done'] as const;

export const PERSON_STATUS_VALUES: readonly PersonStatus[] = ['candidate', 'employee', 'former_employee', 'inactive'] as const;

export const ROLE_STATUS_VALUES: readonly RoleStatus[] = ['Open', 'Staffed', 'Won', 'Lost'] as const;

export const WORK_STATUS_VALUES: readonly WorkStatus[] = ['On Project', 'On Bench', 'Available'] as const;

// ====================================
// TYPE GUARDS
// ====================================

export const isEmployeeStatus = (value: string): value is EmployeeStatus => 
  EMPLOYEE_STATUS_VALUES.includes(value as EmployeeStatus);

export const isJobGrade = (value: string): value is JobGrade => 
  JOB_GRADE_VALUES.includes(value as JobGrade);

export const isOpportunityLevel = (value: string): value is OpportunityLevel => 
  OPPORTUNITY_LEVEL_VALUES.includes(value as OpportunityLevel);

export const isOpportunityStatus = (value: string): value is OpportunityStatus => 
  OPPORTUNITY_STATUS_VALUES.includes(value as OpportunityStatus);

export const isPersonStatus = (value: string): value is PersonStatus => 
  PERSON_STATUS_VALUES.includes(value as PersonStatus);

export const isRoleStatus = (value: string): value is RoleStatus => 
  ROLE_STATUS_VALUES.includes(value as RoleStatus);

export const isWorkStatus = (value: string): value is WorkStatus => 
  WORK_STATUS_VALUES.includes(value as WorkStatus);
